# Generated by Django 4.0.3 on 2022-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starterupperupp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_slogan',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(max_length=55),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_of_contribution',
            field=models.CharField(choices=[('HW', 'Hours worked'), ('MI', 'Money invested')], max_length=2),
        ),
    ]
