# Generated by Django 3.2.10 on 2022-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starterupperupp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='hours_worked',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='investment_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_of_contribution',
            field=models.CharField(choices=[('HW', 'Hours worked'), ('MI', 'Money invested')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
