# Generated by Django 4.0.3 on 2022-04-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starterupperupp', '0002_auto_20220322_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='associated_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starterupperupp.company', to_field='company_name'),
        ),
    ]
