# Generated by Django 4.0.3 on 2022-05-11 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starterupperupp', '0002_alter_company_company_slogan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(max_length=55, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
